package com.taar.dsp

/**
 * Cascaded second-order sections, direct form II transposed — the same structure
 * and ordering `scipy.signal.sosfilt` uses, so coefficients generated by the spike
 * transfer unchanged.
 *
 * Coefficients live in golden/filters.json rather than being designed here. A
 * Butterworth design is not hard, but the filters in the spike are the ones whose
 * behaviour was measured, and re-deriving them on the phone would invite a
 * mismatch nobody would notice.
 */
class Biquad(private val sections: Array<DoubleArray>) {

    init {
        require(sections.isNotEmpty()) { "at least one section required" }
        sections.forEach { require(it.size == 6) { "each section is [b0,b1,b2,a0,a1,a2]" } }
    }

    private val z1 = DoubleArray(sections.size)
    private val z2 = DoubleArray(sections.size)

    fun reset() {
        z1.fill(0.0)
        z2.fill(0.0)
    }

    /** Filters in place is avoided deliberately: callers usually still need the input. */
    fun filter(input: DoubleArray): DoubleArray {
        reset()
        val out = DoubleArray(input.size)
        for (n in input.indices) {
            var x = input[n]
            for (s in sections.indices) {
                val c = sections[s]
                val b0 = c[0]; val b1 = c[1]; val b2 = c[2]
                val a1 = c[4]; val a2 = c[5]
                val y = b0 * x + z1[s]
                z1[s] = b1 * x - a1 * y + z2[s]
                z2[s] = b2 * x - a2 * y
                x = y
            }
            out[n] = x
        }
        return out
    }

    companion object {
        /**
         * Butterworth bandpass 4-16 kHz at 44.1 kHz, and low-pass 500 Hz for the
         * envelope. Both emitted verbatim from golden/filters.json, which was
         * generated by the spike that measured their behaviour. Do not retype these
         * by hand — golden/filters.json also carries each filter's impulse response
         * so GoldenTest can prove the transcription.
         *
         * These are factories, not shared instances: a Biquad carries filter state
         * in z1/z2, so handing the same object to two captures would corrupt both.
         */
        fun hfBandpass4kTo16k() = Biquad(
            arrayOf(
                doubleArrayOf(0.122702625228, 0.245405250456, 0.122702625228, 1.000000000000, 0.559331070855, 0.153697023056),
                doubleArrayOf(1.000000000000, -2.000000000000, 1.000000000000, 1.000000000000, -0.970701932657, 0.288863489899),
                doubleArrayOf(1.000000000000, 2.000000000000, 1.000000000000, 1.000000000000, 1.035227419600, 0.626806319034),
                doubleArrayOf(1.000000000000, -2.000000000000, 1.000000000000, 1.000000000000, -1.434135899878, 0.718450716503),
            )
        )

        fun envLowpass500() = Biquad(
            arrayOf(
                doubleArrayOf(0.001207405190, 0.002414810381, 0.001207405190, 1.000000000000, -1.899333420104, 0.904163040865),
            )
        )
    }
}
